version: "3"
services:
  database-redis:
    container_name: database-redis
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    networks:
      - network

  database-mysql:
    container_name: database-mysql
    depends_on:
      - database-redis
    build:
      context: ./database/mysql
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/react-toy-db-mysql:${TAG_VERSION}
    volumes:
      - ./db/mysql/store:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    restart: always
    networks:
      - network

  spring-app:
    container_name: spring_app
    depends_on:
      - database-mysql
    build:
      context: ./spring-server
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/react-toy-server-spring:${TAG_VERSION}
    ports:
      - "8080:8080"
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
    networks:
      - network

  nginx-react-app:
    container_name: "nginx-react-app"
    depends_on:
      - spring-app
    build:
      context: ./react-client
      dockerfile: Dockerfile
    restart: always
    image: ${DOCKERHUB_USERNAME}/react-toy-client-react:${TAG_VERSION}
    ports:
      - 80:80
    networks:
      - network

  # react-app:
  #   container_name: "react-app"
  #   depends_on:
  #     - spring-app
  #   build:
  #     context: ./react-client
  #     dockerfile: Dockerfile
  #   restart: always
  #   image: ${DOCKERHUB_USERNAME}/react-toy-client-react:${TAG_VERSION}
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - network

networks:
  network:
