server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  redis: # jwt refresh token 저장
    host: database-redis
    port: 6379
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://database-mysql:3306/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

logging:
  level: # TRACE > DEBUG > INFO > WARN > ERROR
    com.example.demo.module: debug
    com.example.demo.config: debug

my:
  jwt:
    access-key: ${JWT_ACCESS_KEY}
    refresh-key: ${JWT_REFRESH_KEY}
